### ISSUE TITLE
Error loading heroes on 1.5.5 release

### ISSUE THREAD

**Issue by xjouvin** [dnchattan/raid-toolkit-public#43]
Hi,
i've just started using raid toolkit (downloaded raid for pc to try it, used to play on mobile).
After starting raid, and then toolkit, i have the following error when loading "heroes" tab : 

I've looked up on logs as requested in an other similar issue, if it can help.
Thanks :-)

```
2021-08-20T19:44:19+0200 <log> index.js:2 (t) [raid-api-worker] 
a [Error]: Could not find l with id '4'
    at l.getById (C:\Users\Utilisateur\AppData\Local\raid-toolkit\app-1.5.5\resources\app.asar\.webpack\main\api.js:2:2872282)
    at u.getGreatHallBonus (C:\Users\Utilisateur\AppData\Local\raid-toolkit\app-1.5.5\resources\app.asar\.webpack\main\api.js:2:2875421)
    at m.getHeroSnapshot (C:\Users\Utilisateur\AppData\Local\raid-toolkit\app-1.5.5\resources\app.asar\.webpack\main\api.js:2:2880642)
    at C:\Users\Utilisateur\AppData\Local\raid-toolkit\app-1.5.5\resources\app.asar\.webpack\main\api.js:2:2879455
    at Array.map (<anonymous>)
    at m.heroes (C:\Users\Utilisateur\AppData\Local\raid-toolkit\app-1.5.5\resources\app.asar\.webpack\main\api.js:2:2879442)
    at S.getHeroes (C:\Users\Utilisateur\AppData\Local\raid-toolkit\app-1.5.5\resources\app.asar\.webpack\main\api.js:2:2813915)
    at t.ProviderServer.call (C:\Users\Utilisateur\AppData\Local\raid-toolkit\app-1.5.5\resources\app.asar\.webpack\main\api.js:2:118309)
    at process.a (C:\Users\Utilisateur\AppData\Local\raid-toolkit\app-1.5.5\resources\app.asar\.webpack\main\api.js:2:108480)
    at process.emit (events.js:327:22)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  type: 'l',
  id: 4
}
```

**Comment by xjouvin** [comment]
any help?
